
title: Beauty zone
email: anton.lafchiev@gmail.com
description: >- # this means to ignore newlines until "baseurl:" 

baseurl: "/beauty" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Toneca99
destination: "docs"
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitignore
  - scss
  - gulpfile.js
  - package-lock.json
  - package.json
  - .vscode
